################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from setuptools import setup

setup(
    name = "zm_proto_cffi",
    version = "0.1.0",
    license = "mpl-2.0",
    description = """Python cffi bindings of: basic messaging for zmon.it""",
    packages = ["zm_proto_cffi", ],
    setup_requires=["cffi"],
    cffi_modules=["zm_proto_cffi/build.py:ffibuilder"],
    install_requires=["cffi"],
)
