################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from __future__ import print_function
import os
import sys

import cffi
ffi = cffi.FFI()

try:
    # If LD_LIBRARY_PATH or your OSs equivalent is set, this is the only way to
    # load the library.  If we use find_library below, we get the wrong result.
    if os.name == 'posix':
        if sys.platform == 'darwin':
            libpath = 'libzm_proto.1.dylib'
        else:
            libpath = 'libzm_proto.so.1'
    elif os.name == 'nt':
        libpath = 'libzm_proto.dll'
    lib = ffi.dlopen(libpath)
except OSError:
    libpath = find_library("zm-proto")
    if not libpath:
        raise ImportError("Unable to find libzm_proto")
    lib = ffi.dlopen(libpath)

from zm_proto_cffi.cdefs import zm_proto_cdefs

for cdef in zm_proto_cdefs:
   ffi.cdef (cdef)
