/*  =========================================================================
    zm-proto - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.  This file is part
    of zmon.it, the fast and scalable monitoring system.                           
                                                                                   
    This Source Code Form is subject to the terms of the Mozilla Public License, v.
    2.0. If a copy of the MPL was not distributed with this file, You can obtain   
    one at http://mozilla.org/MPL/2.0/.                                            

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZM_PROTO_LIBRARY_H_INCLUDED
#define ZM_PROTO_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>

//  ZM_PROTO version macros for compile-time API detection
#define ZM_PROTO_VERSION_MAJOR 1
#define ZM_PROTO_VERSION_MINOR 0
#define ZM_PROTO_VERSION_PATCH 0

#define ZM_PROTO_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZM_PROTO_VERSION \
    ZM_PROTO_MAKE_VERSION(ZM_PROTO_VERSION_MAJOR, ZM_PROTO_VERSION_MINOR, ZM_PROTO_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZM_PROTO_STATIC
#       define ZM_PROTO_EXPORT
#   elif defined ZM_PROTO_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ZM_PROTO_EXPORT __declspec(dllexport)
#       else
#           define ZM_PROTO_EXPORT
#       endif
#   elif defined ZM_PROTO_EXPORTS
#       define ZM_PROTO_EXPORT __declspec(dllexport)
#   else
#       define ZM_PROTO_EXPORT __declspec(dllimport)
#   endif
#   define ZM_PROTO_PRIVATE
#else
#   define ZM_PROTO_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZM_PROTO_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define ZM_PROTO_PRIVATE
#   endif
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
typedef struct _zm_proto_t zm_proto_t;
#define ZM_PROTO_T_DEFINED
typedef struct _zm_proto_utils_t zm_proto_utils_t;
#define ZM_PROTO_UTILS_T_DEFINED


//  Public classes, each with its own header file
#include "zm_proto.h"
#include "zm_proto_utils.h"

#ifdef ZM_PROTO_BUILD_DRAFT_API
//  Self test for private classes
ZM_PROTO_EXPORT void
    zm_proto_private_selftest (bool verbose);
#endif // ZM_PROTO_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
