The following ABNF grammar defines the Basic messaging for zmon.it:

    zm_proto        = *( METRIC | ALERT | DEVICE )

    ;  No description                                                        

    METRIC          = signature %d1 device time ttl ext type value unit
    signature       = %xAA %xA1             ; two octets
    device          = string                ; Device universal unique identifier
    time            = number-8              ; Time when message was generated
    ttl             = number-4              ; Time to live, after $current time > time - ttl, message is droped
    ext             = hash                  ; Additional extended informations for the message
    type            = string                ; Metric name, e.g.: "temperature", "humidity", "power.load", ...
    value           = string                ; Metric value, e.g.: "25.323" or "900".
    unit            = string                ; Metric unit, e.g.: "C" or "F" for temperature, "W" or "kW" for realpower etc...

    ;  No description                                                        

    ALERT           = signature %d2 device time ttl ext rule state severity description
    device          = string                ; Device universal unique identifier
    time            = number-8              ; Time when message was generated
    ttl             = number-4              ; Time to live, after $current time > time - ttl, message is droped
    ext             = hash                  ; Additional extended informations for the message
    rule            = string                ; Identifier of the rule which triggers this alert.
    state           = number-1              ; Alert is active (value 1) or resolved (value 0).
    severity        = number-1              ; Alert is critical (value 1) or not (value 0).
    description     = string                ; Alert description.

    ;  No description                                                        

    DEVICE          = signature %d3 device time ttl ext
    device          = string                ; Device universal unique identifier
    time            = number-8              ; Time when message was generated
    ttl             = number-4              ; Time to live, after $current time > time - ttl, message is droped
    ext             = hash                  ; Additional extended informations for the message

    ; A list of name/value pairs
    hash            = hash-count *( hash-name hash-value )
    hash-count      = number-4
    hash-value      = longstr
    hash-name       = string

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
    number-8        = 8OCTET
